name = "Custom Fedora"
description = "An opinionated Fedora distribution."

# GNOME desktop
[[packages]]
name = "@workstation-product-environment"

# GNOME mail clinet
[[packages]]
name = "evolution"

[[packages]]
name = "nushell"

[[customizations.directories]]
path = "/etc/skel/.config"
mode = "0755"
user = "root"
group = "root"

[[packages]]
name = "vim-enhanced"

[[customizations.directories]]
path = "/etc/skel/.vim"
mode = "0755"
user = "root"
group = "root"

[[customizations.files]]
path = "/etc/skel/.vim/vimrc"
mode = "0644"
user = "root"
group = "root"
data = '''
{{INSERT_VIM_CONFIG}}
'''

[[packages]]
name = "screenfetch"

[[packages]]
name = "tmux"

[[customizations.directories]]
path = "/etc/skel/.config/tmux"
mode = "0755"
user = "root"
group = "root"

[[customizations.files]]
path = "/etc/skel/.config/tmux/tmux.conf"
mode = "0644"
user = "root"
group = "root"
data = '''
{{INSERT_TMUX_CONFIG}}
'''

# Development suit
[[packages]]
name = "cmake"

[[packages]]
name = "make"

[[packages]]
name = "ctags"

[[packages]]
name = "cscope"

[[packages]]
name = "python3-pip"

[[packages]]
name = "pylint"

[[customizations.files]]
path = "/etc/skel/.pylintrc"
mode = "0644"
user = "root"
group = "root"
data = '''
[MAIN]
init-hook="
    import sys, os

    if 'VIRTUAL_ENV' not in os.environ: sys.exit(0)

    ve_dir = os.environ['VIRTUAL_ENV']
    ve_dir in sys.path or sys.path.insert(0, ve_dir)"

extension-pkg-allow-list=PyQt5,numpy
'''

[[packages]]
name = "python3-isort"

# Highlight info
[[packages]]
name = "info"

[[customizations.files]]
path = "/etc/skel/.infokey"
mode = "0644"
user = "root"
group = "root"
data = """
#var
link-style=yellow
active-link-style=yellow,bold
match-style=underline,bold,nocolor
"""

# Desktop icon for commands
[[customizations.directories]]
path = "/etc/skel/.local"
mode = "0755"
user = "root"
group = "root"

[[customizations.directories]]
path = "/etc/skel/.local/share"
mode = "0755"
user = "root"
group = "root"

[[customizations.directories]]
path = "/etc/skel/.local/share/applications"
mode = "0755"
user = "root"
group = "root"

[[customizations.files]]
path = "/etc/skel/.local/share/applications/top.desktop"
mode = "0644"
user = "root"
group = "root"
data = """
[Desktop Entry]
Name=top
Type=Application
Exec=top
Terminal=true
"""
