" Simple and lighweight vim run command file. It only contains one file.
" Author: OctHe
" Copyright (C)
"
" =====================================================================
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
if &compatible
  set nocompatible
endif

" Enable file type detection.
filetype plugin on
" Enable automatic indentation.
filetype indent on

" Try to install minpac
let s:minpac_dir = expand('~/.vim/pack/minpac/opt/minpac')
if !(s:minpac_dir->isdirectory())
  execute '!git clone --depth=1 https://github.com/k-takata/minpac.git' s:minpac_dir
  packadd minpac
endif

function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  " Additional plugins here.

  " starsearch: Enhanced star keymapping. Avoid jumping to next
  call minpac#add('vim-scripts/star-search')
  call minpac#add('vim-scripts/ZoomWin')
  call minpac#add('vim-scripts/DrawIt')
  call minpac#add('vim-scripts/a.vim')
  call minpac#add('vim-scripts/YankRing.vim')
  call minpac#add('vim-scripts/AutoComplPop')
  call minpac#add('vim-scripts/CCTree')
  call minpac#add('vim-scripts/Gundo', {'type': 'opt'})

  " NERDTree: File explorer.
  call minpac#add('preservim/nerdtree')
  call minpac#add('preservim/tagbar')
  call minpac#add('preservim/nerdcommenter')
  call minpac#add('preservim/vim-indent-guides')
  call minpac#add('preservim/vim-pencil')
  call minpac#add('preservim/vimux')

  " vim-tmux-navigator
  " Use local version if it exists
  if isdirectory(glob('~/.local/share/tmux/plugin/vim-tmux-navigator'))
    " Use the same file for both vim and tmux
    call minpac#add('~/.local/share/tmux/plugin/vim-tmux-navigator')
  else
    call minpac#add('christoomey/vim-tmux-navigator')
  endif

  " Show git status in file tree
  call minpac#add('xuyuanp/nerdtree-git-plugin')

  call minpac#add('ludovicchabant/vim-gutentags')

  " surround-like plugin
  call minpac#add('machakann/vim-sandwich')

  call minpac#add('sjl/gundo.vim')

  " Replace auto-pairs with delimitMate. Disable it by default
  call minpac#add('LunarWatcher/auto-pairs', {'type': 'opt'})

  " Automatic closing of quotes, parenthesis, brackets,
  call minpac#add('Raimondi/delimitMate')

  call minpac#add('psliwka/vim-smoothie')

  call minpac#add('timsu92/vim-easymotion')

  call minpac#add('mg979/vim-visual-multi')

  " Align text
  call minpac#add('godlygeek/tabular')

  call minpac#add('ctrlpvim/ctrlp.vim')

  " It does not support virtualtext in vim
  call minpac#add('neomake/neomake')

  call minpac#add('sbdchd/neoformat')

  " Replace autoformat with neoformat since it lacks vim doc. Disable it by default
  if has('python3')
    call minpac#add('vim-autoformat/vim-autoformat', {'type': 'opt'})
  endif

  call minpac#add('vim-airline/vim-airline')

  call minpac#add('rafi/awesome-vim-colorschemes')

endfunction

" ================ Plugin configuration ================
" ---------------- Navigator ----------------
let NERTTreeCaseSensitiveSort = 1
let NERDTreeWinSize = 35

augroup NERDTree
  au!

  " Close vim if the only window left open is a NERDTree
  autocmd BufEnter *
        \ if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()
        \ |   quit
        \ | endif

  " If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
  autocmd BufEnter *
        \ if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1
        \ |   let buf=bufnr('%')
        \ |   buffer#
        \ |   execute "normal! \<C-W>w"
        \ |   execute 'buffer'.buf
        \ | endif
augroup END

" e means explore
nnoremap <silent> <Leader>e :NERDTreeToggle<CR>


let g:yankring_history_dir = '$HOME/.cache/'

" ---------------- Tag and Linter ----------------
let g:neomake_python_enabled_makers = ['pylint']

try
  " When writing a buffer, and on normal mode changes (after 750ms).
  call neomake#configure#automake('nw', 750)
catch
  echo "An error occurred for neomake"
endtry

let g:neoformat_enabled_python = ['isort']

" ---------------- Completor ----------------
let g:delimitMate_balance_matchpairs = 1

let g:NERDSpaceDelims = 1
let g:NERDRemoveExtraSpaces = 1

" ---------------- VCS ----------------

" ---------------- Viewer ----------------
let g:airline#extensions#tabline#enabled = 1        " Enhanced tabline
let g:airline#extensions#tabline#buffer_nr_show = 1 " Show buffer number

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1

" ================ Command ================
" Define user commands for updating/cleaning the plugins.
" Each of them calls PackInit() to load minpac and register
" the information of plugins, then performs the task.
command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#init() | call minpac#status()

" ================ Options ================
syntax enable                          " This enables Vim's syntax-related features.

set hlsearch                           " Highlight the search results
set incsearch                          " Show the pattern while typing

set expandtab                          " Expand tag to space
set tabstop=4                          " One tab includes four spaces
set shiftwidth=4                       " The width of '<' and '>'
set backspace=indent,eol,start         " Allow backspacing over everything in insert mode.

set hidden                             " Hide unsaved buffer
set smartindent                        " Do smart autoindenting
set modeline                           " Modeline is the last comment line if vim is the editor. Use `help modeline` for detail.
set ruler                              " show the cursor position
set wildmenu                           " display completion matches in a status line
set number                             " Show line number
set mouse=a                            " Enable mouse in all mode
set scrolloff=5                        " Show a few lines around the cursor
set fileencodings=utf-8,gb18030,latin1

set background=dark

set colorcolumn=81

try
  " Colorscheme may use plugin
  colorscheme iceberg
catch
  " Builtin colorscheme
  colorscheme desert
endtry

" vim: set sw=2 sts=2 et fdm=marker:
